### ISSUE TITLE
Feature Request: set upload speed

### ISSUE THREAD

**Issue by xpliz** [Hundter/qBittorrent-Ratio-Manager#11]
I would love if I could set different upload speed for different categories. 

Sometimes I need to push some trackers and restrict others. Missing this feature in qbittorent to assign different speeds for different categories/trackers

**Comment by xpliz** [comment]
I just checked qbittorrent API and it seems it supports:

[Get torrent download limit
](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-download-limit)
[Set torrent download limit](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#set-torrent-download-limit)
[Get torrent upload limit](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-upload-limit)
[Set torrent upload limit](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#set-torrent-upload-limit)

**Comment by xpliz** [comment]
I wrote myself a script to handle my needs.

**Comment by xpliz** [comment]
I wrote myself a script to handle my needs.

**Comment by abu-marwa** [comment]
Hey @xpliz , I was thinking about the same idea. Would you mind sharing your script?
