### ISSUE TITLE
Torrents aren't getting deleted

### ISSUE THREAD

**Issue by abu-marwa** [Hundter/qBittorrent-Ratio-Manager#13]
I really like the idea, but upon setting everything up, the torrents aren't being deleted.

I'm running a Debian 12 with Qbittorrent running inside a docker container.
I followed all the instructions during the installation. 
When I run `python3 qbit_ratio_manager.py` and pass the url, username, password and verbosity level 2, I see that everything including login, getting torrents info, properties, trackers goes well with 200 status reply. However, when it comes to the actual deleting, I'm getting 405 status code (method_not_allowed). Here's how it looks:
`DEBUG:urllib3.connectionpool:http://10.100.110.230:8040 "GET /api/v2/torrents/delete?hashes=150f1211d8eb0bcc363be7ea6fae001021d79b1e%7Ca13171c9a9659a4e7255c8ad39b0e80ae2b49d9b&deleteFiles=false HTTP/1.1" 405 18`

According to the [official qBittorrent API documentation](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#general-information), 405 is returned when the wrong request method is used. 

I see that it's been a long time since this repo has been updated, but just in case you'd want to revive it.

Here's the QBT version I'm using:
Qt: | 6.6.1
Libtorrent: | 2.0.9.0
Boost: | 1.82.0
OpenSSL: | 3.1.4
zlib: | 1.3

**Comment by Hundter** [comment]
I pushed a fix that should solve this for you. I don't know if you're planning to use "custom_delete_files_path", but if you are i just wanna stress to be really careful. The QBittorrent devs have changed how the torrent paths are represented in the API before, but I've tried to build security against that into the script.

**Comment by abu-marwa** [comment]
Has anyone ever told you that you're the best Python programmer here on Github? :D
Good job buddy! Swapped both updated files and the script worked like a charm.
I don't think I'll be using "custom_delete_files_path" anytime soon as I'm not consuming the content as fast as I download it, iykwim :D
Thanks for fixing this for me so quickly! You're the GOAT!
