### ISSUE TITLE
Stopped working with public trackers

### ISSUE THREAD

**Issue by BinsonBuzz** [Hundter/qBittorrent-Ratio-Manager#5]
It was working fine last night when it stopped processing public trackers like 9.rarbg.to and open.stealth.si.  I haven't changed my config.

I used the script to create two other versions - 1) set upload speed for torrents from certain trackers and 2) move directory for torrents in certain categories.  Both of those use the scripts core logic, but I just changed the command in remove_torrent_hashes to what I needed.  

Both of those forks have stopped working as well just for public torrents.

I'm using the binhex qbittorrent docker which I don't think updated overnight.

**Comment by Hundter** [comment]
Did you fix it yourself, just wanted to make sure there's no big bug here ;)

**Comment by BinsonBuzz** [comment]
False alarm - sorry it was me being silly and daft.

It's working great and I managed to edit  remove_torrent_hashes to do a few other things - a hatchet job, so not posted on github

**Comment by Hundter** [comment]
Sure thing, i hope the code wasn't too hard to navigate :)
