### ISSUE TITLE
checked 0 torrents?

### ISSUE THREAD

**Issue by xal3xhx** [Hundter/qBittorrent-Ratio-Manager#7]
https://i.imgur.com/Dop2tGG.png

it seams to be login in correctly, how should i go about debugging this?

will it show anything if the qmap files are not setup properly?

**Comment by Hundter** [comment]
It **will** validate the .qman files, however perhaps you have mistyped your category?

**Comment by xal3xhx** [comment]
nope im just a idiot... named files .qmap not .qman :/
thanks for the fast reply tho! i figured it out just as you sent that in

**Comment by Hundter** [comment]
Haha, that's an unfortunate mistake, glad you got it figured out :)

**Comment by xal3xhx** [comment]
sorry to post again but i appear to be having another issue, https://i.imgur.com/bH3TE9z.png

**Comment by Hundter** [comment]
Can you post your .qman file? It seems like the json isn't formatted correctly.

**Comment by xal3xhx** [comment]
`{
    "category": "longterm",
    "public": {
        "min_seed_ratio": 10000,
        "max_seed_ratio": 10000,
        "min_seed_time": 10000,
        "max_seed_time": 10000,
    },
    "private": {
        "min_seed_ratio": 10000,
        "max_seed_ratio": 10000,
        "min_seed_time": 10000,
        "max_seed_time": 10000,
    },
    "delete_files": false,
}`

i also just tested with your example and a similar error occurred

**Comment by xal3xhx** [comment]
ah crap formatting...

**Comment by xal3xhx** [comment]
https://i.imgur.com/d83kBdu.png

**Comment by Hundter** [comment]
The last child of each object should not have a comma at the end, try removing the comma from delete_files and the two max_seed_time lines

**Comment by xal3xhx** [comment]
didn't work, similar error https://i.imgur.com/DMJ2olR.png

**Comment by Hundter** [comment]
Can you send an updated picture of the .qman?

**Comment by xal3xhx** [comment]
https://i.imgur.com/rmY8hDA.png

**Comment by Hundter** [comment]
I can load that file just fine, you don't have any other .qman files in the same folder perhaps?

**Comment by xal3xhx** [comment]
god im dumb.. i blame it on a long day at work..

yeah had another .qman in the folder, just so happens to be your example

thanks for the help and the quick replies <3 
have an amazing day and stay safe!

**Comment by Hundter** [comment]
You too :)
